name:                book-animation
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/book-animation#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2022 Author name here
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - diagrams
  - diagrams-cairo
  - diagrams-lib
  - random
  - random-fu

executables:
  book-animation:
    source-dirs:      src
    main:             Main.hs
